INSERT INTO TECH_SKILLS(SKILL_NAME) VALUES ('HTML-CSS-JAVASCRIPT');
INSERT INTO TECH_SKILLS(SKILL_NAME) VALUES ('ANGULAR');
INSERT INTO TECH_SKILLS(SKILL_NAME) VALUES ('REACT');
INSERT INTO TECH_SKILLS(SKILL_NAME) VALUES ('SPRING');
INSERT INTO TECH_SKILLS(SKILL_NAME) VALUES ('RESTFUL');
INSERT INTO TECH_SKILLS(SKILL_NAME) VALUES ('HIBERNATE');
INSERT INTO TECH_SKILLS(SKILL_NAME) VALUES ('GIT');
INSERT INTO TECH_SKILLS(SKILL_NAME) VALUES ('DOCKER');
INSERT INTO TECH_SKILLS(SKILL_NAME) VALUES ('JENKINS');
INSERT INTO TECH_SKILLS(SKILL_NAME) VALUES ('AWS');

INSERT INTO NON_TECH_SKILLS(SKILL_NAME) VALUES ('SPOKEN');
INSERT INTO NON_TECH_SKILLS(SKILL_NAME) VALUES ('COMMUNICATION');
INSERT INTO NON_TECH_SKILLS(SKILL_NAME) VALUES ('APTITUDE');