CREATE TABLE TECH_SKILLS(
 ID BIGINT NOT NULL AUTO_INCREMENT,
 SKILL_NAME VARCHAR(100) NOT NULL,
 PRIMARY KEY (ID)
);
CREATE TABLE NON_TECH_SKILLS(
 ID BIGINT NOT NULL AUTO_INCREMENT,
 SKILL_NAME VARCHAR(100) NOT NULL,
 PRIMARY KEY (ID)
);